/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ChainlinkClientContract
  extends Truffle.Contract<ChainlinkClientInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ChainlinkClientInstance>;
}

export interface ChainlinkCancelled {
  name: "ChainlinkCancelled";
  args: {
    id: string;
    0: string;
  };
}

export interface ChainlinkFulfilled {
  name: "ChainlinkFulfilled";
  args: {
    id: string;
    0: string;
  };
}

export interface ChainlinkRequested {
  name: "ChainlinkRequested";
  args: {
    id: string;
    0: string;
  };
}

type AllEvents = ChainlinkCancelled | ChainlinkFulfilled | ChainlinkRequested;

export interface ChainlinkClientInstance extends Truffle.ContractInstance {
  methods: {};

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
