/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ENSResolverContract
  extends Truffle.Contract<ENSResolverInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ENSResolverInstance>;
}

type AllEvents = never;

export interface ENSResolverInstance extends Truffle.ContractInstance {
  addr(node: string, txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    addr(node: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
