/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { BadgeContract } from "./Badge";
import { ERC165Contract } from "./ERC165";
import { ERC20Contract } from "./ERC20";
import { ERC721Contract } from "./ERC721";
import { ERC721URIStorageContract } from "./ERC721URIStorage";
import { IBadgeActionContract } from "./IBadgeAction";
import { IBaseModuleContract } from "./IBaseModule";
import { ICoreContract } from "./ICore";
import { IERC165Contract } from "./IERC165";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC721Contract } from "./IERC721";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";
import { TetherUSDTContract } from "./TetherUSDT";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Badge"): BadgeContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721URIStorage"): ERC721URIStorageContract;
      require(name: "IBadgeAction"): IBadgeActionContract;
      require(name: "IBaseModule"): IBaseModuleContract;
      require(name: "ICore"): ICoreContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "TetherUSDT"): TetherUSDTContract;
    }
  }
}

export { BadgeContract, BadgeInstance } from "./Badge";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  ERC721URIStorageContract,
  ERC721URIStorageInstance,
} from "./ERC721URIStorage";
export { IBadgeActionContract, IBadgeActionInstance } from "./IBadgeAction";
export { IBaseModuleContract, IBaseModuleInstance } from "./IBaseModule";
export { ICoreContract, ICoreInstance } from "./ICore";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { TetherUSDTContract, TetherUSDTInstance } from "./TetherUSDT";
