name: autoupdate
on:
  # This will trigger on all pushes to all branches.
  push: {}
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        id: autoupdate
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_CONFLICT_ACTION: "ignore"
          PR_FILTER: labelled
          PR_LABELS: AUTO_UPDATE
          EXCLUDED_LABELS: "dependencies,NO_AUTO_UPDATE"
          MERGE_MSG: "Branch was auto-updated."

      - run: echo 'Merge conflicts found!'
        if: ${{ steps.autoupdate.outputs.conflicted }}

      - run: echo 'No merge conflicts'
        if: ${{ !steps.autoupdate.outputs.conflicted }}
